[fmt]
line_length = 120
tab_width = 2
bracket_spacing = false
int_types = 'long'
quote_style = 'single'
number_underscore = 'thousands'
multiline_func_header = 'params_first'

[profile.default]
solc_version = '0.8.19'
src = 'solidity'
test = 'solidity/test'
out = 'out'
libs = ["node_modules", "lib"]
optimizer_runs = 10_000
bytecode_hash = "none"
cbor_metadata = false

[profile.optimized]
via_ir = true
out = 'out-via-ir'

[profile.test]
via_ir = true
out = 'out-via-ir'
src = 'solidity/test'

[profile.docs]
src = 'solidity/interfaces/'

[fuzz]
runs = 1000

[rpc_endpoints]
mainnet = "${MAINNET_RPC}"
base = "https://mainnet.base.org"
linea = "https://1rpc.io/linea"
metis = "https://andromeda.metis.io/?owner=1088"
